-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "profiles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "profiles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now(),
	"username" text,
	"avatar_url" text,
	"level" bigint DEFAULT '1' NOT NULL,
	"exp" bigint DEFAULT '0' NOT NULL,
	"time_essence" bigint DEFAULT '0' NOT NULL,
	"unclaimed_exp" bigint DEFAULT '0' NOT NULL,
	"unclaimed_time_essence" bigint DEFAULT '0' NOT NULL,
	"accumulated_minutes" bigint DEFAULT '0' NOT NULL,
	"last_daily_claims" timestamp with time zone,
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"onboarding_completed" boolean NOT NULL,
	CONSTRAINT "profiles_username_key" UNIQUE("username"),
	CONSTRAINT "profiles_public_id_key" UNIQUE("public_id")
);
--> statement-breakpoint
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_unlocks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_unlocks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"user_id" bigint NOT NULL,
	"customization_id" bigint NOT NULL,
	"unlocked_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "user_unlocks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "trades" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"sender_id" bigint NOT NULL,
	"receiver_id" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "trades" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "trade_items" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"trade_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" bigint NOT NULL,
	"item_id" bigint NOT NULL,
	"quantity" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "trade_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "tasks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tasks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"user_id" bigint NOT NULL,
	"title" text NOT NULL,
	"target_pomodoro_sessions" smallint DEFAULT '1' NOT NULL,
	"current_pomodoro_session" smallint DEFAULT '0' NOT NULL,
	"is_completed" boolean DEFAULT false NOT NULL,
	"tags" text[],
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"project_id" bigint,
	CONSTRAINT "tasks_public_id_key" UNIQUE("public_id")
);
--> statement-breakpoint
ALTER TABLE "tasks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_settings" (
	"app_settings" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"user_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_settings_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	CONSTRAINT "user_settings_public_id_key" UNIQUE("public_id")
);
--> statement-breakpoint
ALTER TABLE "user_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "shop_offers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text NOT NULL,
	"price" bigint NOT NULL,
	"description" text,
	"label" text,
	"is_active" boolean NOT NULL
);
--> statement-breakpoint
ALTER TABLE "shop_offers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "items_catalog" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "items_catalog_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"category" text NOT NULL,
	"sub_category" text NOT NULL,
	"name" text NOT NULL,
	"sku" text,
	"grade" text,
	"description" text,
	"image_url" text,
	"next_evolution_id" bigint,
	"attributes" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "items_catalog_public_id_key" UNIQUE("public_id"),
	CONSTRAINT "items_catalog_next_evolution_id_key" UNIQUE("next_evolution_id")
);
--> statement-breakpoint
ALTER TABLE "items_catalog" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "levels" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "levels_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"level" bigint NOT NULL,
	"required_exp" bigint NOT NULL,
	CONSTRAINT "levels_level_key" UNIQUE("level")
);
--> statement-breakpoint
ALTER TABLE "levels" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "item_grades" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "item_grades_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"max_level" smallint NOT NULL,
	"base_exp" smallint NOT NULL,
	"exp_multiplier" numeric NOT NULL,
	CONSTRAINT "item_grades_public_id_key" UNIQUE("public_id")
);
--> statement-breakpoint
ALTER TABLE "item_grades" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "ranks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text NOT NULL,
	"min_level" bigint NOT NULL,
	"badge_url" text,
	"attributes" jsonb
);
--> statement-breakpoint
ALTER TABLE "ranks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "shop_offer_rewards" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"offer_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"category" text NOT NULL,
	"item_id" bigint,
	"customization_id" bigint,
	"duration_days" smallint,
	"quantity" smallint DEFAULT '1' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "shop_offer_rewards" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_inventory" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_inventory_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now(),
	"item_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	"current_level" smallint,
	"current_exp" bigint,
	"quantity" bigint DEFAULT '1' NOT NULL,
	"acquired_at" timestamp with time zone NOT NULL,
	"expired_at" timestamp with time zone,
	"instance_states" jsonb
);
--> statement-breakpoint
ALTER TABLE "user_inventory" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "customizations_catalog" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "customizations_catalog_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"category" text NOT NULL,
	"sub_category" text,
	"code" text,
	"description" text,
	"preview_url" text,
	"is_premium" boolean,
	CONSTRAINT "customizations_catalog_code_key" UNIQUE("code")
);
--> statement-breakpoint
ALTER TABLE "customizations_catalog" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pomodoro_sessions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pomodoro_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"task_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	"config_duration" bigint DEFAULT '0' NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	"status" text NOT NULL,
	"reward_blocks_earned" smallint DEFAULT '0' NOT NULL,
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "pomodoro_sessions_public_id_key" UNIQUE("public_id")
);
--> statement-breakpoint
ALTER TABLE "pomodoro_sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "projects" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "projects_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"name" text NOT NULL,
	"size" smallint DEFAULT '0' NOT NULL,
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"image_url" text,
	"description" text,
	"user_id" bigint NOT NULL,
	CONSTRAINT "projects_public_id_key" UNIQUE("public_id")
);
--> statement-breakpoint
ALTER TABLE "projects" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_public_id_fkey" FOREIGN KEY ("public_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user_unlocks" ADD CONSTRAINT "user_unlocks_customization_id_fkey" FOREIGN KEY ("customization_id") REFERENCES "public"."customizations_catalog"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user_unlocks" ADD CONSTRAINT "user_unlocks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "trades" ADD CONSTRAINT "trades_receiver_id_fkey" FOREIGN KEY ("receiver_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "trades" ADD CONSTRAINT "trades_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "trade_items" ADD CONSTRAINT "trade_items_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "public"."profiles"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "trade_items" ADD CONSTRAINT "trade_items_trade_id_fkey" FOREIGN KEY ("trade_id") REFERENCES "public"."trades"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user_settings" ADD CONSTRAINT "user_settings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "items_catalog" ADD CONSTRAINT "items_catalog_next_evolution_id_fkey" FOREIGN KEY ("next_evolution_id") REFERENCES "public"."items_catalog"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "shop_offer_rewards" ADD CONSTRAINT "shop_offer_rewards_customization_id_fkey" FOREIGN KEY ("customization_id") REFERENCES "public"."customizations_catalog"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "shop_offer_rewards" ADD CONSTRAINT "shop_offer_rewards_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "public"."items_catalog"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user_inventory" ADD CONSTRAINT "user_inventory_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "public"."items_catalog"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user_inventory" ADD CONSTRAINT "user_inventory_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "pomodoro_sessions" ADD CONSTRAINT "pomodoro_sessions_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "pomodoro_sessions" ADD CONSTRAINT "pomodoro_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "projects" ADD CONSTRAINT "projects_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE POLICY "Enable insert for users based on user_id" ON "profiles" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((( SELECT auth.uid() AS uid) = public_id));--> statement-breakpoint
CREATE POLICY "Enable users to view their own data only" ON "profiles" AS PERMISSIVE FOR SELECT TO "authenticated";
*/